#!/usr/bin/env python

import socket
import struct
import binascii

"""
function: my_network()
arg: NUID (string)
return: address
"""
def my_network(NUID):
    myID = str(NUID) # cast to string
    address = "10." + myID[2:5] + "." + myID[5:7] + "." + myID[7:9]
    return address


"""
function: my_ethernet()
arg: NUID (string)
return: address
"""
def my_ethernet(NUID):
    myeth = list("020"+str(NUID))
    myeth = '-'.join([i+j for i,j in zip(myeth[::2], myeth[1::2])])
    return myeth
     


# The server will have IP address 10.0.0.1  
# and ethernet address 02:00:00:00:00:01

"""
function: make_ARP()
arg: none
return: 
"""
def make_ARP(): 
    dst_eth = 'FF FF FF FF FF FF/'
    src_eth = my_ethernet('001107800').replace("-","") + "/"
    eth_type = '08 06/'
    hw_type = '00 01 08 00/'
    hw_addr = '06 04/'
    op = '00 01/'
    send_eth = src_eth + "/"
    send_IP = my_network('001107800').replace(".","") +"/"
    targ_eth = '00 00 00 00 00 00/' 
    targ_IP = '0a 00 00 01/'
    padding = '00'*8 + "/"

    arp = dst_eth + src_eth + eth_type + hw_type + hw_addr + op 
    arp += send_eth + send_IP + targ_eth + targ_IP + padding

    return arp.replace(" ","").replace("/","") 


"""
function: make_pkt()
arg:
return:
"""
def make_pkt():
    data = 'GET / HTTP/1.0\r\n\r\n'
    src_port = '10' # arbitrary?
    dst_port = '80'
    src_IP = '' # "as above?"
    dst_IP = '' # "as above?"
    #"ethernet addresses as above"?
    flags = 'SYN'
    window = '1400'
    seq_num = 1
    ack_num = 0
    pkt_id = 2

#TODO: finish setting up the packet


"""
class: ip_pkt
"""
class tcp_pkt:
    def __init__(self):
        self.src_port = '10'
        self.dst_port = '80'
        self.src_IP = ''
        self.dst_IP = ''
        self.flags = 'SYN'
        self.window = '1400'
        self.seq_num = 1
        self.ack_num = 0
        self.pkt_id = 2
        self.checksum = ""#TODO:
        self.data = "" #'GET / HTTP/1.0\r\n\r\n'

class ip_pkt:
    def __init__(self):
        #TODO: IP headers 
        self.data = tcp_pkt() #TODO:
        


"""
Internet checksum
"""
def ip_cksum(pkt):
    if len(pkt) & 1:
        pkt += '\0'
    sum = 0
    for i in range(0, len(pkt)-1, 2):
        sum += struct.unpack_from("!H", pkt, offset=i)[0]
    while (sum > 0xffff):
        sum = (sum & 0xffff) + (sum >> 16)
    return sum ^ 0xffff


"""
function: send()
description: Packet sent over TCP to 'login-faculty.ccs.neu.edu' port 5025. 
            Packets encapsulated using length field 
"""
def send(s, fp):
    
    pkt = make_ARP() #'\1' * 60 # sample packet with bogus addresses and ethertype
    s.connect(('login-faculty.ccs.neu.edu', 5025))
    s.send(struct.pack('!H', len(pkt)) + pkt, 0)
    phdr = struct.pack("IIII", 0, 0, len(pkt), len(pkt))
    fp.write(phdr+pkt)
    print "...packet sent."


"""
function: recv()
description:
"""
def recv(s, fp):
    tmp = s.recv(2, 0)
    n = struct.unpack('!H', tmp)[0] # unpack returns a list
    pkt = ''
    print "receiving packets..."
    while len(pkt) < n:
        pkt += s.recv(n-len(pkt), 0)
    phdr = struct.pack("IIII", 0, 0, len(pkt), len(pkt))
    fp.write(phdr + pkt)
    
    print "ARP response length: " + str(len(pkt))
    print binascii.hexlify(pkt)

    # TODO:
    # 1. while-loop until receive the FIN flag
    # 2. ACK the FIN flag
    # 3. wait for final ACK
    # 4. exit()



"""
function: main()

"""
def main():
    

    fp = open("log.pcap", "w")
    fhdr = struct.pack("IHHIIII", 0xa1b2c3d4, 2, 4, 0, 0, 65536, 1)
    fp.write(fhdr)

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    
    send(s, fp)
    recv(s, fp)
    
    #print make_ARP() 

    s.close()

    #TODO: Create TCP connection with SOCK.RAW, SOCK.IPROTO_RAW
    #TODO: Create IP packet by wrapping a TCP packet
    #TODO: Create functions to increment values in IP packet
"""

"""
if __name__ == "__main__":
        main()
